import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@browser-os/schemas': path.resolve(__dirname, '../../packages/schemas/src'),
      '@browser-os/events': path.resolve(__dirname, '../../packages/events/src'),
      '@browser-os/fs': path.resolve(__dirname, '../../packages/fs/src'),
      '@browser-os/app-registry': path.resolve(__dirname, '../../packages/app-registry/src'),
      '@browser-os/windowing': path.resolve(__dirname, '../../packages/windowing/src'),
      '@browser-os/workspace': path.resolve(__dirname, '../../packages/workspace/src'),
      '@browser-os/taskbar': path.resolve(__dirname, '../../packages/taskbar/src'),
      '@browser-os/notifications': path.resolve(__dirname, '../../packages/notifications/src'),
      '@browser-os/server': path.resolve(__dirname, '../../packages/server/src'),
      '@browser-os/os': path.resolve(__dirname, '../../packages/os/src'),
      '@browser-os/browser': path.resolve(__dirname, '../../system-apps/browser/src'),
      '@browser-os/terminal': path.resolve(__dirname, '../../system-apps/terminal/src'),
      '@browser-os/notepad': path.resolve(__dirname, '../../system-apps/notepad/src'),
      '@browser-os/file-browser': path.resolve(__dirname, '../../system-apps/file-browser/src'),
      '@browser-os/settings': path.resolve(__dirname, '../../system-apps/settings/src'),
      '@browser-os/draw': path.resolve(__dirname, '../../system-apps/draw/src'),
      '@browser-os/calculator': path.resolve(__dirname, '../../system-apps/calculator/src'),
      '@browser-os/clock': path.resolve(__dirname, '../../system-apps/clock/src'),
      '@browser-os/system-monitor': path.resolve(__dirname, '../../system-apps/system-monitor/src'),
      '@browser-os/camera': path.resolve(__dirname, '../../system-apps/camera/src'),
      '@browser-os/music': path.resolve(__dirname, '../../system-apps/music/src'),
      '@browser-os/calendar': path.resolve(__dirname, '../../system-apps/calendar/src'),
      '@browser-os/image-viewer': path.resolve(__dirname, '../../system-apps/image-viewer/src'),
      '@browser-os/video-player': path.resolve(__dirname, '../../system-apps/video-player/src'),
      '@browser-os/contacts': path.resolve(__dirname, '../../system-apps/contacts/src'),
      '@browser-os/weather': path.resolve(__dirname, '../../system-apps/weather/src'),
      '@browser-os/games': path.resolve(__dirname, '../../system-apps/games/src'),
      '@browser-os/screenshot': path.resolve(__dirname, '../../system-apps/screenshot/src'),
      '@browser-os/voice-recorder': path.resolve(__dirname, '../../system-apps/voice-recorder/src'),
      '@browser-os/notes': path.resolve(__dirname, '../../system-apps/notes/src'),
      '@browser-os/todo': path.resolve(__dirname, '../../system-apps/todo/src'),
      '@browser-os/file-search': path.resolve(__dirname, '../../system-apps/file-search/src'),
      '@browser-os/markdown-editor': path.resolve(__dirname, '../../system-apps/markdown-editor/src'),
      '@browser-os/password-manager': path.resolve(__dirname, '../../system-apps/password-manager/src'),
      '@browser-os/pdf-viewer': path.resolve(__dirname, '../../system-apps/pdf-viewer/src'),
      '@browser-os/process-manager': path.resolve(__dirname, '../../system-apps/process-manager/src'),
      '@browser-os/chess': path.resolve(__dirname, '../../system-apps/chess/src'),
      '@browser-os/messaging-client': path.resolve(__dirname, '../../system-apps/messaging-client/src'),
      '@browser-os/email-client': path.resolve(__dirname, '../../system-apps/email-client/src'),
    },
  },
});

