import type { CommandHandler } from '../types';

export const help: CommandHandler = (_args, _flags, _flagValues, _context) => {
  return [
    'Available commands:',
    '',
    'File Operations:',
    '  ls [path] [-l] [-a]     - List directory contents',
    '  cd [path]                - Change directory',
    '  pwd                      - Print working directory',
    '  cat <file>...            - Display file contents',
    '  touch <file>...          - Create empty file or update timestamp',
    '  mkdir <dir>... [-p]      - Create directory',
    '  rm <file>... [-r]        - Remove file or directory',
    '  rmdir <dir>...           - Remove empty directory',
    '  mv <source>... <dest>   - Move/rename file or directory',
    '  cp <source>... <dest> [-r] - Copy file or directory',
    '  find <path> [pattern]   - Search for files/directories',
    '  grep <pattern> <file>... [-i] - Search file contents',
    '',
    'Text Processing:',
    '  head <file>... [-n N]   - Show first N lines (default 10)',
    '  tail <file>... [-n N]   - Show last N lines (default 10)',
    '  wc <file>... [-l] [-w] [-c] - Count lines, words, characters',
    '  sort <file>...           - Sort lines of text',
    '  uniq <file>...           - Remove duplicate lines',
    '',
    'System Information:',
    '  whoami                   - Show current user',
    '  date                     - Show current date/time',
    '  ps                       - List processes (not implemented)',
    '  env                      - Show environment variables',
    '  export VAR=value         - Set environment variable',
    '  unset VAR                - Unset environment variable',
    '',
    'App Launching:',
    '  launch <appId> [args]... - Launch an app',
    '  apps                     - List available apps (not implemented)',
    '',
    'Other:',
    '  help                     - Show this help message',
    '  clear                    - Clear the terminal screen',
    '  echo <text>...           - Print text to the terminal',
    '  history                  - Show command history',
    '',
    'Aliases:',
    '  ll                       - ls -l',
    '  la                       - ls -a',
  ];
};

